assembly_location:
  top_left: [x1, y1, z1, rx, ry, rz]
  top_right: []
  bottom_left: []
  bottom_right: []
  global_right: []
  global_center: []

workspace:
  deliver_space: [x1, y1, z1]
  tool_space: []
  part_space: []
  assembly_space: []